sudo: required
services:
    - docker
    
before_install:
    - docker build -t gampakaushik/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run gampakaushik/react-test npm test -- --coverage
    
after_success:
    - docker build -t gampakaushik/multi-client ./client
    - docker build -t gampakaushik/multi-nginx ./nginx
    - docker build -t gampakaushik/multi-server ./server
    - docker build -t gampakaushik/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push gampakaushik/multi-client
    - docker push gampakaushik/multi-nginx
    - docker push gampakaushik/multi-server
    - docker push gampakaushik/multi-worker